In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
data = pd.read_csv('/Users/oracle/Documents/GitHub/YieldSense-Crop-Yield-Forecasting-Carnegie-Mellon-University/data/external/yield_prediction_dataset.csv')

In [4]:
data

,field_id,date_of_image,latitude,longitude,NDVI,GNDVI,NDWI,SAVI,soil_moisture,temperature,rainfall,crop_type,yield,Unnamed: 13,Unnamed: 14
0,Field_1,01-01-2023,22.625231,88.497925,0.060190,0.084801,-0.084801,0.090280,46.119353,9.884229,1.662354,Rice,40.218031,NaN,NaN
1,Field_1,16-01-2023,22.625231,88.497925,0.213957,0.222009,-0.222009,0.320896,37.542525,13.967073,8.446302,Rice,30.870338,NaN,NaN
2,Field_1,31-01-2023,22.625231,88.497925,0.403306,0.431204,-0.431204,0.604837,24.926279,13.590147,3.862833,Rice,45.330050,NaN,NaN
3,Field_1,15-02-2023,22.625231,88.497925,0.418187,0.444132,-0.444132,0.627144,24.114157,12.343355,16.623542,Rice,49.711781,NaN,NaN
4,Field_1,03-02-2023,22.625231,88.497925,0.375138,0.387985,-0.387985,0.562591,27.420927,11.007707,9.496210,Rice,34.542646,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1620,Field_90,15-06-2023,14.480189,77.593430,0.273514,0.460121,-0.460121,0.410229,24.775243,42.400385,5.595746,Oil Palm,29.441059,NaN,NaN
1621,Field_90,14-08-2023,14.480189,77.593430,0.246901,0.338604,-0.338604,0.370317,31.252223,44.665521,12.928167,Oil Palm,42.701012,NaN,NaN
1622,Field_90,13-10-2023,14.480189,77.593430,0.403294,0.562632,-0.562632,0.604876,18.215152,38.384464,6.514886,Oil Palm,32.842117,NaN,NaN
1623,Field_90,28-10-2023,14.480189,77.593430,0.338009,0.496380,-0.496380,0.506959,22.265011,34.293336,13.097507,Oil Palm,43.838175,NaN,NaN
1624,Field_90,27-12-2023,14.480189,77.593430,0.286447,0.474224,-0.474224,0.429617,23.922958,12.632540,5.678534,Oil Palm,29.722742,NaN,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1625 entries, 0 to 1624
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   field_id       1625 non-null   object
 1   date_of_image  1625 non-null   object
 2   latitude       1625 non-null   float64
 3   longitude      1625 non-null   float64
 4   NDVI           1625 non-null   float64
 5   GNDVI          1625 non-null   float64
 6   NDWI           1625 non-null   float64
 7   SAVI           1625 non-null   float64
 8   soil_moisture  1625 non-null   float64
 9   temperature    1625 non-null   float64
 10  rainfall       1625 non-null   float64
 11  crop_type      1625 non-null   object
 12  yield          1625 non-null   float64
 13  Unnamed: 13    0 non-null      float64
 14  Unnamed: 14    0 non-null      float64
dtypes: float64(12), object(3)
memory usage: 190.6+ KB

In [7]:
data.drop(columns=['Unnamed: 13', 'Unnamed: 14'], inplace=True)

In [8]:
data

,field_id,date_of_image,latitude,longitude,NDVI,GNDVI,NDWI,SAVI,soil_moisture,temperature,rainfall,crop_type,yield
0,Field_1,01-01-2023,22.625231,88.497925,0.060190,0.084801,-0.084801,0.090280,46.119353,9.884229,1.662354,Rice,40.218031
1,Field_1,16-01-2023,22.625231,88.497925,0.213957,0.222009,-0.222009,0.320896,37.542525,13.967073,8.446302,Rice,30.870338
2,Field_1,31-01-2023,22.625231,88.497925,0.403306,0.431204,-0.431204,0.604837,24.926279,13.590147,3.862833,Rice,45.330050
3,Field_1,15-02-2023,22.625231,88.497925,0.418187,0.444132,-0.444132,0.627144,24.114157,12.343355,16.623542,Rice,49.711781
4,Field_1,03-02-2023,22.625231,88.497925,0.375138,0.387985,-0.387985,0.562591,27.420927,11.007707,9.496210,Rice,34.542646
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1620,Field_90,15-06-2023,14.480189,77.593430,0.273514,0.460121,-0.460121,0.410229,24.775243,42.400385,5.595746,Oil Palm,29.441059
1621,Field_90,14-08-2023,14.480189,77.593430,0.246901,0.338604,-0.338604,0.370317,31.252223,44.665521,12.928167,Oil Palm,42.701012
1622,Field_90,13-10-2023,14.480189,77.593430,0.403294,0.562632,-0.562632,0.604876,18.215152,38.384464,6.514886,Oil Palm,32.842117
1623,Field_90,28-10-2023,14.480189,77.593430,0.338009,0.496380,-0.496380,0.506959,22.265011,34.293336,13.097507,Oil Palm,43.838175
1624,Field_90,27-12-2023,14.480189,77.593430,0.286447,0.474224,-0.474224,0.429617,23.922958,12.632540,5.678534,Oil Palm,29.722742

In [9]:
data.sort_values(by='date_of_image', inplace=True)